---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: identity-deployment
  namespace: microservices
  labels:
    app: identity
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: identity
  template:
    metadata:
      labels:
        app: identity
    spec:
      containers:
        - name: identity
          image: devmentors/pacco.services.identity
          ports:
          - containerPort: 80